services:
  _defaults:
    autowire: true
    autoconfigure: true

  a9f\Lifter\:
    resource: ../src/

  a9f\Lifter\LifterApplication:
    public: true

  a9f\Lifter\Upgrade\UpgradeRunner:
    public: true

  a9f\Lifter\Configuration\LifterConfig:
    autowire: false
    shared: true
    lazy: true
